name: task_19
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/